-- Batch telemetry compatibility for the integrated ESP32 controller.
-- Run after 004_admin_controls_and_maps.sql.

create table if not exists public.sensor_telemetry (
  id bigint generated by default as identity primary key,
  controller_device_id text not null,
  slot_id text not null references public.slots(id) on delete cascade,
  distance_cm numeric,
  occupied boolean not null,
  reported_status text not null check (reported_status in ('available','unavailable')),
  received_at timestamptz not null default now()
);

create index if not exists sensor_telemetry_slot_received_idx
  on public.sensor_telemetry(slot_id, received_at desc);

alter table public.sensor_telemetry enable row level security;

-- Default slot-level barriers. Their initial states produce:
-- A1=false, A2=true, A3=false. Admin changes are reflected in later responses.
insert into public.devices(id,name,type,floor,state,status,linked_slot) values
  ('barrier-A1','ไม้กั้นช่อง A1','barrier',1,'closed','online','A1'),
  ('barrier-A2','ไม้กั้นช่อง A2','barrier',1,'open',  'online','A2'),
  ('barrier-A3','ไม้กั้นช่อง A3','barrier',1,'closed','online','A3'),
  ('sensor-A2', 'เซ็นเซอร์ A2', 'sensor', 1,null,    'offline','A2'),
  ('sensor-A3', 'เซ็นเซอร์ A3', 'sensor', 1,null,    'offline','A3')
on conflict(id) do nothing;

create or replace function public.handle_sensor_telemetry(
  device_id text,
  slots jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  slot_item jsonb;
  telemetry_slot text;
  telemetry_dist numeric;
  is_occupied boolean;
  telemetry_state text;
  response_payload jsonb;
begin
  if device_id is null or btrim(device_id) = '' then
    raise exception 'device_id is required';
  end if;
  if slots is null or jsonb_typeof(slots) <> 'array' then
    raise exception 'slots must be a JSON array';
  end if;

  for slot_item in select value from jsonb_array_elements(slots)
  loop
    telemetry_slot := nullif(btrim(slot_item ->> 'slot_id'), '');
    if telemetry_slot is null
       or not exists (select 1 from public.slots s where s.id = telemetry_slot) then
      continue;
    end if;

    telemetry_dist := case
      when jsonb_typeof(slot_item -> 'distance_cm') = 'number'
        then (slot_item ->> 'distance_cm')::numeric
      else null
    end;
    is_occupied := coalesce((slot_item ->> 'occupied')::boolean, false);
    telemetry_state := case when is_occupied then 'unavailable' else 'available' end;

    insert into public.sensor_telemetry(
      controller_device_id, slot_id, distance_cm, occupied, reported_status
    ) values (
      device_id, telemetry_slot, telemetry_dist, is_occupied, telemetry_state
    );

    -- Feed the existing booking lifecycle through its sensor device rows.
    update public.devices d
       set presence = case when is_occupied then 'occupied' else 'empty' end,
           car_present = is_occupied,
           status = 'online',
           updated_at = now()
     where d.type = 'sensor' and d.linked_slot = telemetry_slot;

    -- Do not overwrite reservations or slots under active maintenance.
    update public.slots s
       set status = telemetry_state,
           updated_at = now()
     where s.id = telemetry_slot
       and s.status <> 'booked'
       and not exists (
         select 1 from public.maintenance_logs m
          where m.slot_id = telemetry_slot and m.status = 'open'
       );
  end loop;

  -- Mark an existing controller/device row online when its ID is registered.
  update public.devices d
     set status = 'online', updated_at = now()
   where d.id = device_id;

  -- Return current slot-level barrier states. Defaults preserve the requested
  -- A1=false, A2=true, A3=false response if a barrier row is unavailable.
  select jsonb_build_object(
    'barriers', jsonb_agg(
      jsonb_build_object(
        'slot_id', defaults.slot_id,
        'gate_open', coalesce(barrier.state = 'open', defaults.default_open)
      ) order by defaults.position
    )
  )
  into response_payload
  from (values
    (1, 'A1'::text, false),
    (2, 'A2'::text, true),
    (3, 'A3'::text, false)
  ) as defaults(position, slot_id, default_open)
  left join lateral (
    select d.state
      from public.devices d
     where d.type = 'barrier' and d.linked_slot = defaults.slot_id
     order by d.updated_at desc
     limit 1
  ) barrier on true;

  return response_payload;
end;
$$;

revoke all on function public.handle_sensor_telemetry(text,jsonb) from public;
grant execute on function public.handle_sensor_telemetry(text,jsonb) to anon, authenticated, service_role;
comment on function public.handle_sensor_telemetry(text,jsonb) is
  'Stores batch sensor telemetry, updates the existing lifecycle state, and returns slot barrier commands.';
